hashtags = {
"#MAGA" : "#MakeAmericaGreatAgain",
"#KeepAmericaGreat" : "#MakeAmericaGreatAgain",
"#KAG" : "#MakeAmericaGreatAgain",
"#AmericaFirst" : "#MakeAmericaGreatAgain",
"#AmericansFirst" : "#MakeAmericaGreatAgain",
"#BuildTheWallNow" : "#BuildTheWall",
"#BuildThatWall" : "#BuildTheWall",
"#BuildTheDamnWall" : "#BuildTheWall",
"#RedNationRising" : "#VoteRed",
"#BigRedWave" : "#VoteRed",
"#RedWave" : "#VoteRed",
"#RedWaveRising" : "#VoteRed",
"#VoteDemsOut" : "#WalkAway",
"#WalkAwayMovementGrowing" : "#WalkAway",
"#WalkAwayMovement" : "#WalkAway",
"#WalkAwayFromDemocrats" : "#WalkAway",
"#SendThemHome" : "#DeportThemAll",
"#SendThemBack" : "#DeportThemAll",
"#DeportIllegals" : "#DeportThemAll",
"#DeportIllegalAliens" : "#DeportThemAll",
"#DeportIllegalImmigrants" : "#DeportThemAll",
"#Deport" : "#DeportThemAll",
"#EndDACA" : "#NoDACA",
"#SecureUSBorders" : "#KeepAmericansSafe",
"#KeepAmericaSafe" : "#KeepAmericansSafe",
"#ProtectUSCitizens" : "#KeepAmericansSafe",
"#ProtectUS" : "#KeepAmericansSafe",
"#ProtectUSA" : "#KeepAmericansSafe",
"#ProtectAmerica" : "#KeepAmericansSafe",
"#BlueLivesMatter" : "#BackTheBlue"
}
caplist = {"EU", "CIA", "FBI", "NSA", "ICE", "GOP", "USA", "US", "UK", "DACA", "POTUS", "NRA", "SNL", "UN", "TV", "OK", "NFL", "<NUM>", "<USER>"}
slang = {
"gonna" : "going to",
"wanna" : "want to",
"imma" : "i am going to",
"i'mma" : "i am going to",
"lmao" : "laughing my ass off",
"lol" : "laughing out loud",
"idc" : "i do not care",
"idk" : "i do not know",
"smh" : "shaking my head",
" u " : " you ",
" ur " : " your ",
" r " : " are ",
"yo" : "your",
"stfu" : "shut the fuck up",
"gtfo" : "get the fuck out",
"ya" : "you",
"da" : "the",
"sum" : "something",
" n " : "and",
" y " : "why",
" gf " : "girlfriend",
" bf " : "boyfriend",
" af " : "as fuck",
"wtf" : "what the fuck",
"lil" : "little"

}
